version: "3.8"

services:
  app:
    build: .
    container_name: tic-tac-toe-app
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - db
    restart: on-failure
    command: >
      sh -c "
      goose -dir ./migrations postgres \"$DATABASE_URL\" up &&
      ./app
      "

  db:
    image: postgres:16-alpine
    container_name: tic-tac-toe-db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pg:
